"""
Column Detection Patterns
=======================
Regex patterns for auto-detecting financial column types.
Expanded for Healthcare, Real Estate, HR, Marketing, Education, Manufacturing, Logistics.
"""

COLUMN_PATTERNS: dict[str, list[str]] = {
    "revenue": [
        r"revenue",
        r"sales",
        r"income",
        r"gross.*sales",
        r"total.*sales",
        r"mrr",
        r"arr",
        r"monthly.*recurring",
        r"annual.*recurring",
        r"amount",            # catch "Amount", "Total Amount", "Net Amount"
        r"total.*amount",
        r"unit.?price",       # UnitPrice, unit_price
        r"price",             # SalePrice, ListPrice
        r"sale.?price",
        r"list.?price",
        r"invoice.?amount",
        r"gmv",
        r"turnover",
        r"proceeds",
        r"net.?sales",
        r"bill.+amount",
    ],
    "cost": [
        r"cost",
        r"expense",
        r"cogs",
        r"opex",
        r"spend",
        r"payment",
        r"price",
        r"fee",
        r"charge",
        r"unit.?cost",
        r"total.?cost",
        r"treatment.?cost",
    ],
    "profit": [r"profit", r"margin", r"earnings", r"ebitda", r"net.*income"],
    "customer_id": [
        r"customer.*id",
        r"client.*id",
        r"user.*id",
        r"account.*id",
        r"member.*id",
        r"subscriber.*id",
    ],
    "employee_id": [
        r"employee.*id",
        r"staff.*id",
        r"worker.*id",
        r"personnel.*id",
    ],
    "student_id": [
        r"student.*id",
        r"pupil.*id",
        r"applicant.*id",
    ],
    "patient_id": [
        r"patient.*id",
        r"health.*id",
        r"medical.*id",
    ],
    "property_id": [
        r"property.*id",
        r"parcel.*id",
        r"listing.*id",
        r"unit.*id",
    ],
    "shipment_id": [
        r"shipment.*id",
        r"tracking.*id",
        r"carrier.*id",
        r"waybill.*id",
    ],
    "customer_count": [
        r"customers?$",
        r"clients?$",
        r"users?$",
        r"subscribers?$",
        r"accounts?$",
        r"members?$",
        r"employee.?count",
        r"patient.?count",
        r"student.?count",
        r"headcount",
    ],
    "date": [
        r"date",
        r"created.*at",
        r"updated.*at",
        r"timestamp",
        r"time",
        r"period",
        r"month",
        r"year",
        r"quarter",
        r"enrollment.?date",
        r"admission.?date",
        r"discharge.?date",
        r"hire.?date",
        r"production.?date",
        r"delivery.?date",
        r"ship.?date",
    ],
    "transaction_id": [
        r"transaction.*id",
        r"order.*id",
        r"order.?number",
        r"invoice.*id",
        r"invoice.?no",
        r"payment.*id",
        r"reference",
        r"ref.?number",
        r"po.?number",
    ],
    "quantity": [
        r"quantity",
        r"qty",
        r"count",
        r"units",
        r"items",
        r"volume",
        r"units.?produced",
        r"defect.?count",
    ],
    "churn": [r"churn", r"cancel", r"churned", r"inactive", r"lost", r"attrition"],
    "retention": [r"retention", r"retained", r"active", r"renewed"],
    "acquisition_cost": [
        r"cac",
        r"acquisition.*cost",
        r"marketing.*spend",
        r"ad.*spend",
    ],
    "cash": [r"cash", r"balance", r"bank", r"funds", r"liquidity"],
    # ── Domain-specific column types ────────────────────────────────────
    # Healthcare
    "diagnosis": [
        r"diagnosis",
        r"dx.?code",
        r"icd.?code",
        r"condition",
        r"procedure.?code",
    ],
    "length_of_stay": [
        r"length.?of.?stay",
        r"los",
        r"stay.?duration",
        r"inpatient.?days",
    ],
    "readmission": [
        r"readmit",
        r"readmission",
        r"rehospitalized",
        r"re.?admitted",
    ],
    # Real Estate
    "bedrooms": [
        r"bedrooms?",
        r"beds",
        r"bed.?count",
        r"num.?bedrooms?",
    ],
    "bathrooms": [
        r"bathrooms?",
        r"baths",
        r"bath.?count",
        r"num.?bathrooms?",
    ],
    "square_feet": [
        r"square.?feet",
        r"sq.?ft",
        r"sqft",
        r"floor.?area",
        r"total.?area",
        r"land.?area",
        r"lot.?size",
    ],
    "days_on_market": [
        r"days.?on.?market",
        r"dom",
        r"listing.?days",
        r"time.?to.?sell",
        r"market.?duration",
    ],
    # HR
    "salary": [
        r"salary",
        r"wages?",
        r"compensation",
        r"pay.?rate",
        r"hourly.?rate",
        r"annual.?pay",
        r"base.?pay",
    ],
    "performance": [
        r"performance.?score",
        r"rating",
        r"review.?score",
        r"eval.?score",
        r"kpi.?score",
        r"goal.?attainment",
    ],
    "tenure": [
        r"tenure",
        r"years.?at.?company",
        r"years.?of.?service",
        r"employment.?duration",
        r"seniority",
    ],
    # Marketing
    "impressions": [
        r"impressions?",
        r"reach",
        r"views?",
        r"page.?views?",
    ],
    "clicks": [
        r"clicks?",
        r"click.?through",
        r"ctr",
        r"tap",
    ],
    "conversions": [
        r"conversions?",
        r"conversion.?rate",
        r"signups?",
        r"registrations?",
        r"leads?",
    ],
    "marketing_spend": [
        r"ad.?spend",
        r"marketing.?spend",
        r"campaign.?cost",
        r"cpm",
        r"cpc",
        r"roas",
    ],
    # Manufacturing
    "yield": [
        r"yield",
        r"yield.?rate",
        r"yield.?pct",
        r"first.?pass.?yield",
        r"fpy",
        r"defect.?rate",
    ],
    "cycle_time": [
        r"cycle.?time",
        r"processing.?time",
        r"throughput.?time",
        r"lead.?time",
        r"dwell.?time",
    ],
    "defect": [
        r"defect",
        r"defect.?count",
        r"rework",
        r"scrap",
        r"reject",
        r"fail.?rate",
    ],
    # Education
    "gpa": [
        r"gpa",
        r"grade.?point",
        r"grade.?average",
    ],
    "grade": [
        r"grade",
        r"score",
        r"marks?",
        r"exam.?score",
        r"test.?score",
        r"final.?grade",
    ],
    "attendance": [
        r"attendance",
        r"absent",
        r"present",
        r"tard(y|ies)",
        r"enrollment.?rate",
    ],
    # Logistics
    "weight": [
        r"weight",
        r"mass",
        r"tonnage",
        r"load.?weight",
        r"ship.?weight",
    ],
    "distance": [
        r"distance",
        r"mileage",
        r"kilometers",
        r"miles",
        r"shipping.?distance",
        r"route.?distance",
    ],
    "delivery_time": [
        r"delivery.?time",
        r"transit.?time",
        r"ship.?time",
        r"lead.?time",
        r"on.?time",
        r"delay",
    ],
    "carrier": [
        r"carrier",
        r"shipper",
        r"courier",
        r"freight.?company",
        r"ship.?via",
        r"transport.?mode",
    ],
    # Automotive
    "mileage": [
        r"mileage",
        r"odometer",
        r"kms.driven",
        r"distance.driven",
    ],
    "engine_size": [
        r"engine.?size",
        r"engine.?cc",
        r"engine.?capacity",
        r"displacement",
        r"cc$",
    ],
    "fuel_type": [
        r"fuel.?type",
        r"fuel$",
        r"petrol",
        r"diesel",
        r"gasoline",
        r"hybrid",
        r"electric",
    ],
    "transmission": [
        r"transmission",
        r"gearbox",
        r"auto(matic)?",
        r"manual",
        r"drivetrain",
    ],
    "mpg": [
        r"(?<!per.)mpg$",
        r"fuel.?economy",
        r"consumption",
    ],
    "horsepower": [
        r"horsepower",
        r"bhp",
        r"power.?output",
        r"ps$",
        r"torque",
    ],
    "vehicle_model": [
        r"vehicle.?model",
        r"make",
        r"brand",
        r"manufacturer",
        r"trim",
        r"variant",
        r"model$",
    ],
    "num_owners": [
        r"owners?$",
        r"prev(ious)?.?owners?",
    ],
}
