"""
Chat Schemas (Core)
-------------------
These schemas define the contracts for:
- Chat messages sent by the user
- Responses generated by the AI engine
- Optional chart payloads
- RAG (retrieval) state flags

They are used by:
- Conversation service
- Chat API routes
- LLM + retrieval pipelines
"""

from pydantic import BaseModel, Field
from typing import Optional, Dict, Any


# ---------------------------------------------------
# Base Config
# ---------------------------------------------------
class _Config:
    orm_mode = True
    extra = "forbid"
    use_enum_values = True


# ---------------------------------------------------
# CHAT REQUEST
# ---------------------------------------------------
class ChatRequest(BaseModel):
    """
    User message payload.
    - message: User input text
    - context: Optional conversation context (e.g. dashboard embeddings)
    - conversation_id: Existing conversation for multi-turn chat
    """
    message: str = Field(..., min_length=1)
    context: Optional[Dict[str, Any]] = None
    conversation_id: Optional[str] = None

    class Config(_Config):
        pass


# ---------------------------------------------------
# CHAT RESPONSE
# ---------------------------------------------------
class ChatResponse(BaseModel):
    """
    AI response payload.
    - response: Plain text from LLM
    - chart: Optional chart config (if chart is generated from chat)
    - metadata_used: Whether dataset metadata was referenced
    - rag_used: Whether vector search/retrieval was used
    """
    response: str
    chart: Optional[Dict[str, Any]] = None
    metadata_used: bool = False
    rag_used: bool = False

    class Config(_Config):
        pass


# ---------------------------------------------------
# Export
# ---------------------------------------------------
__all__ = [
    "ChatRequest",
    "ChatResponse"
]
